/**
 * Codama workflow entry point for @rewardz/sdk.
 *
 * ─── NEW WORKFLOW (Codama fully integrated) ─────────────────────────────────
 *
 * The TypeScript client in `src/generated/` is now AUTO-GENERATED by Codama
 * from the annotated Rust source in `mvp-smart-contracts/api/`.
 *
 * To regenerate the client:
 *
 *   # From mobileSpecs/sdk/ (workspace root):
 *   pnpm codama              # Full pipeline: IDL generation + client generation
 *
 *   # Or step by step:
 *   pnpm generate-idl        # Runs: cargo check --features idl -p rewardz-mvp-api
 *   pnpm generate-clients    # Runs: tsx scripts/generate-clients.ts
 *
 * ─── HOW IT WORKS ───────────────────────────────────────────────────────────
 *
 * 1. IDL generation (Rust → JSON):
 *    - State structs in `mvp-smart-contracts/api/src/state/` use #[derive(CodamaAccount)]
 *    - Instructions in `api/src/instruction.rs` use #[derive(CodamaInstructions)]
 *    - `api/build.rs` runs Codama::load() and writes `mvp-smart-contracts/idl/rewardz-mvp.json`
 *
 * 2. Client generation (JSON → TypeScript):
 *    - `sdk/scripts/generate-clients.ts` reads the IDL
 *    - `sdk/scripts/lib/rewardz-mvp-codama-builder.ts` applies transforms:
 *        • appendAccountDiscriminator — prepend disc+version u8 fields
 *        • appendPdaDerivers — add PDA nodes for all 6 account types
 *        • setInstructionAccountDefaultValues — program IDs + PDA defaults
 *        • updateInstructionBumps — bump defaults for PDA-creating instructions
 *    - @codama/renderers-js renders @solana/kit TypeScript client
 *    - Output: `packages/sdk/src/generated/` (DO NOT hand-edit)
 *
 * ─── CUSTOM LAYOUT NOTE ─────────────────────────────────────────────────────
 *
 * The REWARDZ MVP program uses a custom 2-byte prefix layout
 * (discriminator_u8 + version_u8) with field-sequential byte encoding —
 * NOT standard Borsh. Codama generates sequential struct decoders that match
 * the documented field offsets in `api/src/state/`. The appendAccountDiscriminator
 * transform handles the 2-byte prefix.
 *
 * ─── AFTER PROGRAM DEPLOYMENT ───────────────────────────────────────────────
 *
 * 1. Update the program ID in `mvp-smart-contracts/api/src/lib.rs`:
 *    pinocchio::address::declare_id!("<REAL_DEPLOYED_ADDRESS>");
 *
 * 2. Update REWARDZ_PROGRAM_ID in:
 *    `sdk/scripts/lib/updates/set-instruction-account-default-values.ts`
 *
 * 3. Re-run: pnpm codama
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Show status of the generated IDL.
const idlPath = join(__dirname, 'idl', 'rewardz-mvp.json');
try {
  const idl = JSON.parse(readFileSync(idlPath, 'utf-8'));
  const p = idl.program;
  console.log(`IDL: ${p.name} v${p.version}`);
  console.log(`  Program ID: ${p.publicKey}`);
  console.log(`  Accounts: ${p.accounts.length}`);
  console.log(`  Instructions: ${p.instructions.length}`);
  console.log();
  console.log('To regenerate: cd .. && pnpm codama');
} catch {
  console.log('IDL not found. Run: cd .. && pnpm codama');
}
