/**
 * Generate TypeScript client for @rewardz/sdk from the Codama IDL.
 *
 * Workflow:
 *   1. Read IDL from mvp-smart-contracts/idl/rewardz-mvp.json
 *      (generated by: cargo check --features idl -p rewardz-mvp-api)
 *   2. Apply REWARDZ-specific Codama transforms (discriminator, PDAs, defaults)
 *   3. Render @solana/kit TypeScript client into packages/sdk/src/generated/
 *
 * Run via: pnpm generate-clients
 * Or full pipeline: pnpm codama  (runs generate-idl then generate-clients)
 */

import type { AnchorIdl } from '@codama/nodes-from-anchor';
import { renderVisitor as renderJavaScriptVisitor } from '@codama/renderers-js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import { createRewardzMvpCodamaBuilder } from './lib/rewardz-mvp-codama-builder.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const sdkRoot = path.join(__dirname, '..');

// IDL is generated by cargo check --features idl in mvp-smart-contracts/api/
const idlPath = path.join(sdkRoot, '..', 'mvp-smart-contracts', 'idl', 'rewardz-mvp.json');

if (!fs.existsSync(idlPath)) {
  console.error(`IDL not found at: ${idlPath}`);
  console.error('Run first: pnpm generate-idl');
  process.exit(1);
}

const rawIdl = JSON.parse(fs.readFileSync(idlPath, 'utf-8')) as AnchorIdl;
const outputDir = path.join(sdkRoot, 'packages', 'sdk', 'src', 'generated');

console.log(`Reading IDL from: ${idlPath}`);
console.log(`Writing client to: ${outputDir}`);

const codama = createRewardzMvpCodamaBuilder(rawIdl)
  .appendAccountDiscriminator()
  .appendPdaDerivers()
  .setInstructionAccountDefaultValues()
  .updateInstructionBumps()
  .build();

// Also copy the IDL to the SDK package so it stays in sync.
const sdkIdlDir = path.join(sdkRoot, 'packages', 'sdk', 'idl');
fs.mkdirSync(sdkIdlDir, { recursive: true });
fs.copyFileSync(idlPath, path.join(sdkIdlDir, 'rewardz-mvp.json'));
console.log(`IDL copied to: ${sdkIdlDir}/rewardz-mvp.json`);

void codama.accept(
  renderJavaScriptVisitor(outputDir, {
    deleteFolderBeforeRendering: true,
    formatCode: true,
  }),
);

console.log('Done. TypeScript client generated successfully.');
